### ISSUE TITLE
ImportError: cannot import name 'TypedDict' from 'typing'

### ISSUE THREAD

**Issue by tyleralgigi** [mrtolkien/leaguepedia_parser#9]
Trying to run the example code give in the readme and this is the error im getting

      Traceback (most recent call last):
        File "c:/Users/tyler/OneDrive/Desktop/apps/gamepedia.py", line 8, in <module>
          import leaguepedia_parser
        File "C:\Users\tyler\AppData\Local\Programs\Python\Python37\lib\site-packages\leaguepedia_parser\__init__.py", line 1, in <module>
          from leaguepedia_parser.parsers.game_parser import get_regions, get_tournaments, get_games, get_game_details
        File "C:\Users\tyler\AppData\Local\Programs\Python\Python37\lib\site-packages\leaguepedia_parser\parsers\game_parser.py", line 4, in <module>
          from lol_dto.classes.game import LolGame
        File "C:\Users\tyler\AppData\Local\Programs\Python\Python37\lib\site-packages\lol_dto\__init__.py", line 1, in <module>
          import lol_dto.classes
        File "C:\Users\tyler\AppData\Local\Programs\Python\Python37\lib\site-packages\lol_dto\classes\__init__.py", line 1, in <module>
          import lol_dto.classes.game
        File "C:\Users\tyler\AppData\Local\Programs\Python\Python37\lib\site-packages\lol_dto\classes\game\__init__.py", line 1, in <module>
          from lol_dto.classes.game.lol_game import LolGame
        File "C:\Users\tyler\AppData\Local\Programs\Python\Python37\lib\site-packages\lol_dto\classes\game\lol_game.py", line 1, in <module>
          from typing import TypedDict, Dict, List, Optional
      ImportError: cannot import name 'TypedDict' from 'typing' (C:\Users\tyler\AppData\Local\Programs\Python\Python37\lib\typing.py)

**Comment by mrtolkien** [comment]
Wrong python version
